# Generated by Django 6.0.6 on 2026-07-05 15:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formerly_known_as', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=10, verbose_name='PAN')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_account_no', models.CharField(blank=True, max_length=30, verbose_name='Bank Account No.')),
                ('neft_ifsc', models.CharField(blank=True, max_length=11, verbose_name='NEFT/IFSC Code')),
                ('msme_no', models.CharField(blank=True, max_length=50, verbose_name='MSME No.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('_seq', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('challan_no', models.CharField(blank=True, max_length=50)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-_seq'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=5)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(blank=True, max_length=10, verbose_name='HSN Code')),
                ('description', models.CharField(max_length=300)),
                ('make', models.CharField(blank=True, help_text='e.g. MAKE - 3M', max_length=100)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('NOS', 'NOS'), ('PCS', 'PCS'), ('MTR', 'MTR'), ('KG', 'KG'), ('BOX', 'BOX'), ('SET', 'SET'), ('RFT', 'RFT'), ('PKT', 'PKT'), ('OTH', 'Other')], default='NOS', max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5, verbose_name='CGST Rate %')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5, verbose_name='SGST Rate %')),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.party'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('NEFT/RTGS', 'NEFT/RTGS'), ('UPI', 'UPI'), ('Other', 'Other')], default='NEFT/RTGS', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.party')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
